apiVersion: v1
kind: PersistentVolume
metadata:
  name: prometheus-pv
  namespace: monitoring
  labels:
    app: prometheus-pv
    adi10hero.monitoring: prometheus-pv
spec:
  storageClassName: monitoring
  capacity:
    storage: 1Gi
  accessModes:
  - ReadWriteMany
  hostPath:
    path: "/usr/share/monitoring_data/prometheus"
