---
#check kubelet is running or not
- name: check for kubelet
  shell: "systemctl status kubelet"
  register: _svc_kubelet
  failed_when: _svc_kubelet.rc != 0 and ("could not be found" not in _svc_kubelet.stderr)

#IF KUBELET IS RUNNING, THEN
#reset k8s
- name: reset k8s
  command: kubeadm reset -f
  when: "_svc_kubelet.rc == 0"

