global:
route:
  receiver: "webhook"
  group_by: ['alertname']
  group_wait: 1s
  group_interval: 5s
  repeat_interval: 5s
  routes:
  - match:
      severity: critical

receivers:
- name: "webhook"
  webhook_configs:
  - url: 'http://10.104.29.96:5000/alerts' #change this with your url
    send_resolved: true

