---
#Worker

- name: Copying token to worker nodes
  copy: src={{ token_file }} dest=join_token

- name: Joining worker nodes with kubernetes master
  shell: |
   kubeadm reset -f
   cat join_token | tail -1 > out.sh
   sh out.sh