global:
  scrape_interval:     15s
  evaluation_interval: 15s

rule_files:
  - "alert.rules"

scrape_configs:
  - job_name: 'collectd-exporter'
    scrape_interval: 5s
    static_configs:
      - targets: ['10.99.43.9:9103']

  - job_name: 'cadvisor'
    scrape_interval: 5s
    static_configs:
      - targets: ['10.107.74.242:8080']

  - job_name: 'prometheus'
    scrape_interval: 10s
    static_configs:
      - targets: ['localhost:9090']
    
alerting:
  alertmanagers:
  - scheme: http
    static_configs:
    - targets: 
      - '10.98.47.134:9093'

