apiVersion: v1
kind: Service
metadata:
  labels:
    adi10hero.monitoring: alertmanager1
    app: alertmanager1
  name: alertmanager1
  namespace: monitoring
  annotations:
      prometheus.io/scrape: 'true'
      prometheus.io/path:   /
      prometheus.io/port:   '8080'

spec:
  selector: 
    app: alertmanager1
    adi10hero.monitoring: alertmanager1
  type: NodePort
  ports:
  - name: "9093"
    port: 9093
    targetPort: 9093
    nodePort: 30931
  - name: "6783"
    port: 6783
    targetPort: 6783
    nodePort: 30678

