kind: ConfigMap
apiVersion: v1
metadata:
  name: alertmanager-config
  namespace: monitoring
data:
  config.yml: |-
    global:
    route:
      receiver: "webhook"
      group_by: ['alertname', 'priority']
      group_wait: 1s
      group_interval: 5s
      repeat_interval: 5s
      routes:
      - match:
          severity: critical

    receivers:
    - name: "webhook"
      webhook_configs:
      - url: 'https://webhook.site/34334e8a-6cf5-4897-90a9-6c29756fdbbc'
        send_resolved: true
