apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: alertmanager1
    adi10hero.monitoring: alertmanager1
  name: alertmanager1
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: alertmanager1
      adi10hero.monitoring: alertmanager1
  strategy:
    type: Recreate
  template:
    metadata:
      name: alertmanager1
      labels:
        app: alertmanager1
        adi10hero.monitoring: alertmanager1 
    spec:
      containers:
      - name: alertmanager1
        image: prom/alertmanager
        args:
        - --config.file=/etc/alertmanager/config.yml
        - --storage.path=/alertmanager
        - --cluster.peer=alertmanager:6783
        - --cluster.listen-address=0.0.0.0:6783
        ports:
        - containerPort: 9093
        # - containerPort: 9094
        - containerPort: 6783
        securityContext:
          runAsUser: 0
        volumeMounts:
        - name: config-volume
          mountPath: /etc/alertmanager
        - name: alertmanager
          mountPath: /alertmanager
      restartPolicy: Always
      volumes:
      - name: config-volume
        configMap:
          name: alertmanager1-config
      - name: alertmanager
        emptyDir: {}
