apiVersion: apps/v1
kind: Deployment
metadata:
  name: collectd-exporter
  namespace: monitoring
  labels:
    app: collectd-exporter
    adi10hero.monitoring: collectd-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: collectd-exporter
      adi10hero.monitoring: collectd-exporter
  strategy:
    type: Recreate  
  template:
    metadata:
      name: collectd-exporter
      labels:
        app: collectd-exporter
        adi10hero.monitoring: collectd-exporter
    spec:
      containers:
      - args:
        - --collectd.listen-address=0.0.0.0:25826
        image: prom/collectd-exporter
        name: collectd-exporter
        ports:
        - containerPort: 9103
        - containerPort: 25826
          protocol: UDP
        securityContext:
          runAsUser: 0
      restartPolicy: Always
      volumes: null

