apiVersion: v1
kind: Service
metadata:
  name: collectd-exporter
  namespace: monitoring
  labels:
    app: collectd-exporter
    adi10hero.monitoring: collectd-exporter
spec:
  ports:
  - name: "9103"
    port: 9103
    nodePort: 30103
  - name: "25826"
    port: 25826
    protocol: UDP
    nodePort: 30826
  selector:
    app: collectd-exporter
    adi10hero.monitoring: collectd-exporter
  type: NodePort
