apiVersion: v1
kind: PersistentVolume
metadata:
  name: db-pv
  namespace: monitoring
  labels:
    app: db-pv
    adi10hero.monitoring: db-pv
spec:
  storageClassName: monitoring
  capacity:
    storage: 6Gi
  accessModes:
  - ReadWriteMany
  hostPath:
    path: "/usr/share/monitoring_data/db"
