apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-pvc
  namespace: monitoring
  labels:
    app: grafana-pvc
    adi10hero.monitoring: grafana-pvc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: monitoring
  resources:
    requests:
      storage: 4Gi
  selector:
    matchLabels:
      app: grafana-pv
      adi10hero.monitoring: grafana-pv
