apiVersion: v1
kind: PersistentVolume
metadata:
  name: grafana-pv
  namespace: monitoring
  labels:
    app: grafana-pv
    adi10hero.monitoring: grafana-pv
spec:
  storageClassName: monitoring
  capacity:
    storage: 5Gi
  accessModes:
  - ReadWriteMany
  nfs:
    server: 10.10.120.211
    path: "/usr/share/monitoring_data/grafana"
