apiVersion: v1
kind: Service
metadata:
  labels:
    adi10hero.monitoring: prometheus1
    app: prometheus1
  name: prometheus1
  namespace: monitoring
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/port:   '9090'
spec:
  type: NodePort 
  ports:
  - name: prometheus1
    protocol: TCP
    port: 9090
    nodePort: 30901
  selector:
    adi10hero.monitoring: prometheus1
    app: prometheus1
