kind: ConfigMap
apiVersion: v1
metadata:
  name: alertmanager-config
  namespace: monitoring
data:
  config.yml: |-
    global:
    route:
      receiver: "webhook"
      group_by: ['alertname', 'priority']
      group_wait: 1s
      group_interval: 5s
      repeat_interval: 5s
      routes:
      - match:
          severity: critical

    receivers:
    - name: "webhook"
      webhook_configs:
      - url: 'http://10.10.120.202:5000/alerts' #change later...
        send_resolved: true
