apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert --volumes hostPath
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: cadvisor
  name: cadvisor
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: cadvisor
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert --volumes hostPath
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.service: cadvisor
    spec:
      containers:
      - image: gcr.io/google-containers/cadvisor
        imagePullPolicy: ""
        name: cadvisor
        ports:
        - containerPort: 8080
        resources: {}
        securityContext:
          privileged: true
        volumeMounts:
        - mountPath: /rootfs
          name: cadvisor-hostpath0
          readOnly: true
        - mountPath: /var/run
          name: cadvisor-hostpath1
        - mountPath: /sys
          name: cadvisor-hostpath2
          readOnly: true
        - mountPath: /sys/fs/cgroup
          name: cadvisor-hostpath3
          readOnly: true
        - mountPath: /dev/disk
          name: cadvisor-hostpath4
          readOnly: true
        - mountPath: /var/lib/docker
          name: cadvisor-hostpath5
          readOnly: true
      restartPolicy: Always
      serviceAccountName: ""
      volumes:
      - hostPath:
          path: /
        name: cadvisor-hostpath0
      - hostPath:
          path: /var/run
        name: cadvisor-hostpath1
      - hostPath:
          path: /sys
        name: cadvisor-hostpath2
      - hostPath:
          path: /cgroup
        name: cadvisor-hostpath3
      - hostPath:
          path: /dev/disk/
        name: cadvisor-hostpath4
      - hostPath:
          path: /var/lib/docker/
        name: cadvisor-hostpath5
status: {}
