apiVersion: apps/v1
kind: Deployment
metadata:
  name: cadvisor
  namespace: monitoring
  labels:
    adi10hero.monitoring: cadvisor
    app: cadvisor
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cadvisor
      adi10hero.monitoring: cadvisor
  strategy:
    type: Recreate
  template:
    metadata:
      name: cadvisor
      labels:
        adi10hero.monitoring: cadvisor
        app: cadvisor
    spec:
      containers:
      - image: gcr.io/google-containers/cadvisor
        name: cadvisor
        ports:
        - containerPort: 8080
        securityContext:
          runAsUser: 0
        volumeMounts:
        - mountPath: /rootfs
          name: cadvisor-hostpath0
          readOnly: true
        - mountPath: /var/run
          name: cadvisor-hostpath1
        - mountPath: /sys
          name: cadvisor-hostpath2
          readOnly: true
        - mountPath: /sys/fs/cgroup
          name: cadvisor-hostpath3
          readOnly: true
        - mountPath: /dev/disk
          name: cadvisor-hostpath4
          readOnly: true
        - mountPath: /var/lib/docker
          name: cadvisor-hostpath5
          readOnly: true
      restartPolicy: Always
      volumes:
      - hostPath:
          path: /
        name: cadvisor-hostpath0
      - hostPath:
          path: /var/run
        name: cadvisor-hostpath1
      - hostPath:
          path: /sys
        name: cadvisor-hostpath2
      - hostPath:
          path: /cgroup
        name: cadvisor-hostpath3
      - hostPath:
          path: /dev/disk/
        name: cadvisor-hostpath4
      - hostPath:
          path: /var/lib/docker/
        name: cadvisor-hostpath5

