apiVersion: v1
kind: Service
metadata:
  labels:
    app: cadvisor
    adi10hero.monitoring: cadvisor
  name: cadvisor
  namespace: monitoring
spec:
  ports:
  - name: "8080"
    port: 8080
    targetPort: 8080
  selector:
    app: cadvisor
    adi10hero.monitoring: cadvisor
