apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert --volumes hostPath
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: collectd-exporter
  name: collectd-exporter
spec:
  ports:
  - name: "9103"
    port: 9103
    targetPort: 9103
  - name: "25826"
    port: 25826
    protocol: UDP
    targetPort: 25826
  selector:
    io.kompose.service: collectd-exporter
status:
  loadBalancer: {}
