apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: monitoring
  labels:
    app: postgres
    adi10hero.monitoring: postgres
spec:
  selector:
    app: postgres
    adi10hero.monitoring: postgres
  type: ClusterIP
  ports:
  - name: "postgres-port"
    port: 5432
    targetPort: 5432


