apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: monitoring
  labels:
    app: grafana
    adi10hero.monitoring: grafana
  annotations:
      prometheus.io/scrape: 'true'
      prometheus.io/port:   '3000'
spec:
  selector:
    app: grafana
    adi10hero.monitoring: grafana
  type: NodePort
  ports:
  - name: "3000"
    port: 3000
    targetPort: 3000
    nodePort: 30000

