apiVersion: v1
kind: Service
metadata:
  labels:
    adi10hero.monitoring: prometheus
  name: prometheus
  namespace: monitoring
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/port:   '9090'
spec:
  type: NodePort 
  ports:
  - name: prometheus
    protocol: TCP
    port: 9090
    nodePort: 30900
  selector:
    adi10hero.monitoring: prometheus
