apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert --volumes hostPath
    kompose.version: 1.21.0 (992df58d8)
  labels:
    io.kompose.service: prometheus
  name: prometheus
spec:
  replicas: 2
  selector:
    matchLabels:
      io.kompose.service: prometheus
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert --volumes hostPath
        kompose.version: 1.21.0 (992df58d8)
      labels:
        io.kompose.service: prometheus
    spec:
      containers:
      - args:
        - --config.file=/etc/prometheus/prometheus.yml
        - --storage.tsdb.path=/prometheus
        - --web.console.libraries=/etc/prometheus/console_libraries
        - --web.console.templates=/etc/prometheus/consoles
        image: prom/prometheus
        imagePullPolicy: ""
        name: prometheus
        ports:
        - containerPort: 9090
        resources: {}
        securityContext:
          runAsUser: 0
        volumeMounts:
        - mountPath: /etc/prometheus
          name: prometheus-hostpath0
        - mountPath: /prometheus
          name: prometheus-data
      restartPolicy: Always
      serviceAccountName: ""
      volumes:
      - hostPath:
          path: /root/PAG_K8S/prometheus
        name: prometheus-hostpath0
      - hostPath:
          path: /root/PAG_K8S
        name: prometheus-data
