apiVersion: apps/v1
kind: Deployment
metadata:
  name: webhook
  namespace: monitoring
  labels:
    app: webhook
    adi10hero.monitoring: webhook
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webhook
      adi10hero.monitoring: webhook
  strategy:
    type: Recreate 
  template:
    metadata:
      labels:
        app: webhook
        adi10hero.monitoring: webhook
    spec:
      containers:
      - image: adi10hero/simple-webhook-reciever
        name: webhook
        ports:
        - containerPort: 5000
        securityContext:
          privileged: true
      restartPolicy: Always
      volumes: null
