apiVersion: v1
kind: Service
metadata:
  name: webhook
  namespace: monitoring
  labels:
    app: webhook
    adi10hero.monitoring: webhook
spec:
  type: NodePort
  ports:
  - name: "5000"
    port: 5000
    targetPort: 5000
    nodePort: 30500
  selector:
    app: webhook
    adi10hero.monitoring: webhook
